site_name: Jianping Meng
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
    - C++
    - Fortran
    - Bash
  features:
    - content.code.copy
    - content.action.edit

  # This enables choice of light/dark mode
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  # This needs mkdocs-pdf
  - mkdocs-pdf
  - search
  # This needs mkdocs-git-revision-date-localized-plugin
  - git-revision-date-localized:
      enable_creation_date: true


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md




