name: Deploy MkDocs Site

# Trigger on pushes to main branch
on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocs-pdf mkdocs-git-revision-date-localized-plugin pymdown-extensions mkdocs-minify-plugin
          #mkdocs-toggle-sidebar-plugin # Add other MkDocs plugins here

      - name: Build site
        run: mkdocs build  # Generates static files in 'site' folder

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'  # Path to MkDocs output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
